### ISSUE TITLE
Possible XSS

### ISSUE THREAD

**Issue by styfle** [ooade/PreactStatic#1]
Does [this line](https://github.com/ooade/PreactStatic/blob/3774fd54ead00fb75563f657f7fc5059de6d9fc5/server/index.js#L27) escape angle brackets?

I have a [project](https://github.com/styfle/react-server-example-tsx#preventing-xss) with SSR and decided to do 1 more HTTP request to avoid XSS. So I'm curious how you are solving this problem.

**Comment by ooade** [comment]
No. It doesn't. I'll fix that now. Thanks. I would probably strip off tags... Like:
```js
<script>window.__STATE__=${JSON.stringify(state).replace(/<|>/g, '')}</script>
```
